### Swap two rows
#### Description
Given m and n, swap the mth and nth rows of the 2-D NumPy array given below.

a =<br> 
[[4 3 1]<br>
 [5 7 0]<br>
 [9 9 3]<br>
[8 2 4]]<br>

#### Example:
Input 1:<br>
0<br>
2<br>
Output 1:<br>
[[9 9 3] <br>
 [5 7 0] <br>
 [4 3 1] <br>
 [8 2 4]]

In [2]:
import numpy as np 

# Given array
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])

# Read the values of m and n
import sys
m = int(input('Enter value of m: '))
n = int(input('Enter value of m: '))

a[[m,n]] = a[[n,m]]

print(a)

Enter value of m: 1
Enter value of m: 2
[[4 3 1]
 [9 9 3]
 [5 7 0]
 [8 2 4]]


### Description
#### Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

Note: Make sure the array is of type int.

#### Example:
Input 1:<br>
4<br>
Output 1:<br>
[[1 1 1 1]<br>
[1 0 0 1]<br>
[1 0 0 1]<br>
[1 1 1 1]]<br>
Input 2:<br>
2<br>
Output 2:<br>
[[1 1] <br>
 [1 1]] 

In [3]:
import numpy as np

n = int(input('Enter a number: '))

a = np.ones((n, n), dtype=int)
a[1:-1, 1:-1] = 0
print(a)


Enter a number: 10
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


#### Filtering based on conditions
Suppose in ‘ipl18’, you want to filter out the teams that have an NRR greater than zero, and for which the ‘For’ score exceeds the ‘Against’ score, i.e. both the conditions should be satisfied. Which teams will be left after you perform the above filtration? 

In [6]:
import pandas as pd

ipl18 = pd.DataFrame({'Team': ['SRH', 'CSK', 'KKR', 'RR', 'MI', 'RCB', 'KXIP', 'DD'],
                      'Matches': [14, 14, 14, 14, 14, 14, 14, 14],
                      'Won': [9, 9, 8, 7, 6, 6, 6, 5],
                      'Lost': [5, 5, 6, 7, 8, 8, 8, 9],
                      'Tied': [0, 0, 0, 0, 0, 0, 0, 0],
                      'N/R': [0, 0, 0, 0, 0, 0, 0, 0],
                      'Points': [18, 18, 16, 14, 12, 12, 12, 10],
                      'NRR': [0.284, 0.253, -0.070, -0.250, 0.317, 0.129, -0.502, -0.222],
                      'For': [2230, 2488, 2363, 2130, 2380, 2322, 2210, 2297],
                      'Against': [2193, 2433, 2425, 2141, 2282, 2383, 2259, 2304]},
                     index=range(1, 9)
                     )

print(ipl18[(ipl18['NRR'] > 0) & (ipl18['For'] > ipl18['Against'])])

  Team  Matches  Won  Lost  Tied  N/R  Points    NRR   For  Against
1  SRH       14    9     5     0    0      18  0.284  2230     2193
2  CSK       14    9     5     0    0      18  0.253  2488     2433
5   MI       14    6     8     0    0      12  0.317  2380     2282


#### Operations on multiple dataframes
If all the stats are taken for both ‘ipl17’ and ‘ipl18’, which team with its total points greater than 25 will have the highest win percentage?

In [8]:
import pandas as pd

ipl17 = pd.DataFrame({'Team': ['MI', 'RPS', 'SRH', 'KKR', 'KXIP', 'DD', 'GL', 'RCB'],
                         'Matches': [14, 14, 14, 14, 14, 14, 14, 14],
                         'Won': [10, 9, 8, 8, 7, 6, 4, 3],
                         'Lost': [4, 5, 5, 6, 7, 8, 10, 10],
                         'Tied': [0, 0, 0, 0, 0, 0, 0, 0],
                         'N/R': [0, 0, 1, 0, 0, 0, 0, 1],
                         'Points': [20, 18, 17, 16, 14, 12, 8, 7],
                         'NRR': [0.784, 0.176, 0.469, 0.641, 0.123, -0.512, -0.412, -1.299],
                         'For': [2407, 2180, 2221, 2329, 2207, 2219, 2406, 1845],
                         'Against': [2242, 2165, 2118, 2300, 2229, 2255, 2472, 2033]},
                         index = range(1,9)
                    )
print(ipl18)
print(ipl17)

   Team  Matches  Won  Lost  Tied  N/R  Points    NRR   For  Against
1   SRH       14    9     5     0    0      18  0.284  2230     2193
2   CSK       14    9     5     0    0      18  0.253  2488     2433
3   KKR       14    8     6     0    0      16 -0.070  2363     2425
4    RR       14    7     7     0    0      14 -0.250  2130     2141
5    MI       14    6     8     0    0      12  0.317  2380     2282
6   RCB       14    6     8     0    0      12  0.129  2322     2383
7  KXIP       14    6     8     0    0      12 -0.502  2210     2259
8    DD       14    5     9     0    0      10 -0.222  2297     2304
   Team  Matches  Won  Lost  Tied  N/R  Points    NRR   For  Against
1    MI       14   10     4     0    0      20  0.784  2407     2242
2   RPS       14    9     5     0    0      18  0.176  2180     2165
3   SRH       14    8     5     0    1      17  0.469  2221     2118
4   KKR       14    8     6     0    0      16  0.641  2329     2300
5  KXIP       14    7     7     0 

In [11]:
ipl18.set_index('Team', inplace=True)
ipl17.set_index('Team', inplace=True)
ipl_17_18 = ipl18.add(ipl17, fill_value=0, )
ipl_17_18 = ipl_17_18[ipl_17_18['Points'] > 25]
ipl_17_18['win_percentage'] = 100 * (ipl_17_18['Won'] / ipl_17_18['Matches'])

print(ipl_17_18[ipl_17_18['win_percentage'] == ipl_17_18['win_percentage'].max()])

      Matches   Won  Lost  Tied  N/R  Points    NRR     For  Against  \
Team                                                                   
SRH      28.0  17.0  10.0   0.0  1.0    35.0  0.753  4451.0   4311.0   

      win_percentage  
Team                  
SRH        60.714286  
